# Generated by Django 6.0.5 on 2026-05-15 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationPrenatale',
            fields=[
                ('rapport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.rapport')),
                ('service_nom', models.CharField(default='Service de Gynecologie-Obstetrique', max_length=200)),
                ('cpn1', models.IntegerField(default=0)),
                ('cpn2', models.IntegerField(default=0)),
                ('cpn3', models.IntegerField(default=0)),
                ('cpn4', models.IntegerField(default=0)),
                ('cpn5_plus', models.IntegerField(default=0)),
                ('consultations_postnatales', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rapport CPN',
                'verbose_name_plural': 'Rapports CPN',
            },
            bases=('core.rapport',),
        ),
    ]
