# Generated by Django 6.0.5 on 2026-05-15 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urgence',
            fields=[
                ('rapport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.rapport')),
                ('service_nom', models.CharField(default='Service des Urgences', max_length=200)),
                ('nb_lits', models.IntegerField(default=0, verbose_name='Nombre de lits')),
                ('nb_lits_fonctionnels', models.IntegerField(default=0, verbose_name='Nombre de lits fonctionnels')),
                ('nb_journees_theoriques', models.IntegerField(default=0, verbose_name='Nombre de journées théoriques')),
                ('nb_journees_realisees', models.IntegerField(default=0, verbose_name='Nombre de journées réalisées')),
                ('taux_occupation', models.FloatField(default=0, verbose_name="Taux d'occupation (%)")),
                ('delai_moyen_pec', models.FloatField(default=0, verbose_name='Délai moyen de prise en charge (heures)')),
                ('assurance_cmu', models.IntegerField(default=0, verbose_name='Patients CMU')),
                ('assurance_privee', models.IntegerField(default=0, verbose_name='Assurance privée')),
            ],
            options={
                'verbose_name': 'Rapport des urgences',
                'verbose_name_plural': 'Rapports des urgences',
            },
            bases=('core.rapport',),
        ),
        migrations.CreateModel(
            name='MorbiditeUrgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche_age', models.CharField(choices=[('0-4', '0-4 ans'), ('5-9', '5-9 ans'), ('10-14', '10-14 ans'), ('15-19', '15-19 ans'), ('20-24', '20-24 ans'), ('25-49', '25-49 ans'), ('50+', '50 ans et plus')], max_length=10)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('pathologie', models.CharField(max_length=255, verbose_name='Pathologie')),
                ('nombre', models.IntegerField(default=0, verbose_name='Nombre')),
                ('urgence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morbidites', to='urgences.urgence')),
            ],
        ),
        migrations.CreateModel(
            name='CauseDecesUrgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche_age', models.CharField(choices=[('0-4', '0-4 ans'), ('5-9', '5-9 ans'), ('10-14', '10-14 ans'), ('15-19', '15-19 ans'), ('20-24', '20-24 ans'), ('25-49', '25-49 ans'), ('50+', '50 ans et plus')], max_length=10)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('cause', models.CharField(max_length=255, verbose_name='Cause probable du décès')),
                ('nombre', models.IntegerField(default=0, verbose_name='Nombre')),
                ('urgence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causes_deces', to='urgences.urgence')),
            ],
        ),
        migrations.CreateModel(
            name='FrequentationUrgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche_age', models.CharField(choices=[('0-4', '0-4 ans'), ('5-9', '5-9 ans'), ('10-14', '10-14 ans'), ('15-19', '15-19 ans'), ('20-24', '20-24 ans'), ('25-49', '25-49 ans'), ('50+', '50 ans et plus')], max_length=10)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('nb_admis', models.IntegerField(default=0, verbose_name='Patients admis')),
                ('nb_observes', models.IntegerField(default=0, verbose_name='Patients en observation/hospitalisés')),
                ('nb_refere', models.IntegerField(default=0, verbose_name='Patients référé')),
                ('nb_retour_domicile', models.IntegerField(default=0, verbose_name='Retours à domicile')),
                ('nb_deces', models.IntegerField(default=0, verbose_name='Décès')),
                ('urgence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequentations', to='urgences.urgence')),
            ],
            options={
                'unique_together': {('urgence', 'tranche_age', 'sexe')},
            },
        ),
    ]
