# Generated by Django 6.0.5 on 2026-05-15 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accouchement',
            fields=[
                ('rapport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.rapport')),
                ('service_nom', models.CharField(default='Service de Gynécologie-Obstétrique', max_length=200)),
                ('accouchements_domicile', models.IntegerField(default=0, verbose_name='Accouchements à domicile')),
                ('accouchements_normal', models.IntegerField(default=0, verbose_name='Accouchement normal (voie basse)')),
                ('accouchements_cesarienne', models.IntegerField(default=0, verbose_name='Accouchement par césarienne')),
                ('autres_accouchements', models.IntegerField(default=0, verbose_name="Autres types d'accouchements")),
                ('mort_nes', models.IntegerField(default=0, verbose_name='Mort-nés')),
                ('naissances_vivantes', models.IntegerField(default=0, verbose_name='Naissances vivantes')),
                ('hypotrophie', models.IntegerField(default=0, verbose_name='Hypotrophie à la naissance (poids < 2500g)')),
                ('deces_maternel', models.IntegerField(default=0, verbose_name='Décès maternel')),
                ('deces_neonatal', models.IntegerField(default=0, verbose_name='Décès néonatal')),
            ],
            options={
                'verbose_name': "Rapport d'accouchement",
                'verbose_name_plural': "Rapports d'accouchements",
            },
            bases=('core.rapport',),
        ),
    ]
