# Generated by Django 6.0.5 on 2026-05-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('termine', 'Terminé'), ('valide', 'Validé'), ('en_ligne', 'En ligne')], default='brouillon', max_length=20),
        ),
    ]
