# Generated by Django 6.0.5 on 2026-05-15 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('rapport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.rapport')),
                ('service_nom', models.CharField(default='Service non spécifié', max_length=200)),
                ('provenance_secondaire', models.IntegerField(default=0)),
                ('provenance_tertiaire', models.IntegerField(default=0)),
                ('non_refere', models.IntegerField(default=0)),
                ('assurance_cmu', models.IntegerField(default=0)),
                ('assurance_privee', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rapport de consultation',
                'verbose_name_plural': 'Rapports de consultation',
            },
            bases=('core.rapport',),
        ),
        migrations.CreateModel(
            name='DiagnosticRetenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche_age', models.CharField(choices=[('0-4', '0-4 ans'), ('5-9', '5-9 ans'), ('10-14', '10-14 ans'), ('15-19', '15-19 ans'), ('20-24', '20-24 ans'), ('25-49', '25-49 ans'), ('50+', '50 ans et plus')], max_length=10)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('code_diagnostic', models.CharField(blank=True, max_length=50, null=True)),
                ('libelle_diagnostic', models.CharField(max_length=255)),
                ('nombre', models.IntegerField(default=0)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='consultations.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='MotifConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche_age', models.CharField(choices=[('0-4', '0-4 ans'), ('5-9', '5-9 ans'), ('10-14', '10-14 ans'), ('15-19', '15-19 ans'), ('20-24', '20-24 ans'), ('25-49', '25-49 ans'), ('50+', '50 ans et plus')], max_length=10)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('libelle_motif', models.CharField(max_length=255)),
                ('nombre', models.IntegerField(default=0)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motifs', to='consultations.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='TrancheAgeActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche_age', models.CharField(choices=[('0-4', '0-4 ans'), ('5-9', '5-9 ans'), ('10-14', '10-14 ans'), ('15-19', '15-19 ans'), ('20-24', '20-24 ans'), ('25-49', '25-49 ans'), ('50+', '50 ans et plus')], max_length=10)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('nombre', models.IntegerField(default=0)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='consultations.consultation')),
            ],
            options={
                'unique_together': {('consultation', 'tranche_age', 'sexe')},
            },
        ),
    ]
